name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: System Profiler
      run: system_profiler SPHardwareDataType
    - name: CPU Stats
      run: |
        system_profiler SPHardwareDataType | grep Cores:
    - name: RAM Stats
      run: |
        system_profiler SPHardwareDataType | grep "  Memory:"
    - name: Disk Stats # diskutil info -all
      run: |
        df -P
