name: Ubuntu Benchmarker

on:
  workflow_dispatch:

jobs:
  Demo:
    runs-on: ubuntu-latest

    steps:
      - name: Machine Stats
        run: |
          lscpu | grep '^CPU(s):'
          cat /proc/meminfo | grep MemTotal
          df -h | grep /mnt
          
      - name: Install Benchmark Tools
        run: |
          sudo apt install sysbench --assume-yes
          sudo apt install fio --assume-yes
        
      - name: Run CPU Benchmark
        run: sysbench cpu --threads=32 --events=1000000 --time=120 run
          
      - name: Run Disk Benchmark
        run: fio --name TEST --eta-newline=5s --filename=temp.file --rw=randrw --size=2g --io_size=512m --blocksize=4k --ioengine=libaio --fsync=1 --iodepth=1 --direct=1 --numjobs=32 --runtime=120 --group_reporting
